import { Dentist } from "@/app/(public)/_components/module/DentistAllComponents/types";

// Centralized Demo Dentist Data
export const DEMO_DENTISTS: Dentist[] = [
  {
    id: "dr-ava-johnson",
    name: "Dr. Ava Johnson",
    slug: "dr-ava-johnson",
    specialty: "Veneers Specialist",
    imageSeed: "ava-johnson",
    image: "https://i.pravatar.cc/150?u=ava-johnson",
    rating: 5.0,
    reviewCount: 45,
    location: "Mexico City, Mexico",
    city: "Mexico City",
    country: "Mexico",
    price: 1500,
    rdvScore: 100,
    verified: true,
    licenseNo: "MX-2847361",
    procedures: ["Porcelain Veneers", "Cosmetic Dentistry", "Smile Design"],
    tags: ["No Surprise Guarantee", "EN - ES"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.4326, lng: -99.1332 },
  },
  {
    id: "dr-sarah-thompson",
    name: "Dr. Sarah Thompson",
    slug: "dr-sarah-thompson",
    specialty: "Orthodontist",
    imageSeed: "sarah-thompson",
    image: "https://i.pravatar.cc/150?u=sarah-thompson",
    rating: 4.9,
    reviewCount: 48,
    location: "Polanco, Mexico City",
    city: "Polanco",
    country: "Mexico",
    price: 1500,
    rdvScore: 100,
    verified: true,
    licenseNo: "MX-9928172",
    procedures: ["Dental Implants", "Aligners", "Teeth Whitening"],
    tags: ["No Surprise Guarantee", "EN - ES"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.4326, lng: -99.1733 },
  },
  {
    id: "dr-emily-carter",
    name: "Dr. Emily Carter",
    slug: "dr-emily-carter",
    specialty: "Restorative Dentist",
    imageSeed: "emily-carter",
    image: "https://i.pravatar.cc/150?u=emily-carter",
    rating: 4.9,
    reviewCount: 31,
    location: "Roma Norte, Mexico City",
    city: "Roma Norte",
    country: "Mexico",
    price: 1350,
    rdvScore: 98,
    verified: true,
    licenseNo: "MX-1122334",
    procedures: ["Dental Crowns", "Porcelain Veneers", "Full Smile Makeover"],
    tags: ["Same Day Booking", "EN - ES"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.4146, lng: -99.1622 },
  },
  {
    id: "dr-julian-mora",
    name: "Dr. Julian Mora",
    slug: "dr-julian-mora",
    specialty: "Implant Dentist",
    imageSeed: "julian-mora",
    image: "https://i.pravatar.cc/150?u=julian-mora",
    rating: 4.8,
    reviewCount: 29,
    location: "Roma Norte, Mexico City",
    city: "Roma Norte",
    country: "Mexico",
    price: 1600,
    rdvScore: 96,
    verified: true,
    licenseNo: "MX-8877665",
    procedures: ["Dental Implants", "Dental Bridges", "Bone Grafting"],
    tags: ["No Surprise Guarantee", "EN"],
    languages: ["English"],
    coords: { lat: 19.4098, lng: -99.1568 },
  },
  {
    id: "dr-ana-lopez",
    name: "Dr. Ana Lopez",
    slug: "dr-ana-lopez",
    specialty: "Cosmetic Dentist",
    imageSeed: "ana-lopez",
    image: "https://i.pravatar.cc/150?u=ana-lopez",
    rating: 4.7,
    reviewCount: 22,
    location: "Coyoacan, Mexico City",
    city: "Coyoacan",
    country: "Mexico",
    price: 1200,
    rdvScore: 94,
    verified: true,
    licenseNo: "MX-5544332",
    procedures: ["Teeth Whitening", "Smile Design", "Full Smile Makeover"],
    tags: ["EN - ES", "Weekend Availability"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.3509, lng: -99.1611 },
  },
  {
    id: "dr-isaac-reyes",
    name: "Dr. Isaac Reyes",
    slug: "dr-isaac-reyes",
    specialty: "General Dentist",
    imageSeed: "isaac-reyes",
    image: "https://i.pravatar.cc/150?u=isaac-reyes",
    rating: 4.6,
    reviewCount: 18,
    location: "Del Valle, Mexico City",
    city: "Del Valle",
    country: "Mexico",
    price: 980,
    rdvScore: 92,
    verified: true,
    licenseNo: "MX-2233441",
    procedures: ["Teeth Whitening", "Dental Crowns", "Dental Implants"],
    tags: ["Family Friendly", "EN - ES"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.3847, lng: -99.1629 },
  },
  {
    id: "dr-lucia-gomez",
    name: "Dr. Lucia Gomez",
    slug: "dr-lucia-gomez",
    specialty: "Periodontist",
    imageSeed: "lucia-gomez",
    image: "https://i.pravatar.cc/150?u=lucia-gomez",
    rating: 4.5,
    reviewCount: 15,
    location: "Napoles, Mexico City",
    city: "Napoles",
    country: "Mexico",
    price: 1100,
    rdvScore: 90,
    verified: true,
    licenseNo: "MX-7788990",
    procedures: ["Porcelain Veneers", "Full Smile Makeover", "Smile Design"],
    tags: ["Flexible Schedule", "EN - ES"],
    languages: ["English", "Spanish"],
    coords: { lat: 19.3929, lng: -99.1768 },
  },
  {
    id: "dr-michael-chen",
    name: "Dr. Michael Chen",
    slug: "dr-michael-chen",
    specialty: "Orthodontist",
    imageSeed: "michael-chen",
    image: "https://i.pravatar.cc/150?u=michael-chen",
    rating: 4.8,
    reviewCount: 36,
    location: "San Angel, Mexico City",
    city: "San Angel",
    country: "Mexico",
    price: 1450,
    rdvScore: 97,
    verified: true,
    licenseNo: "MX-4455667",
    procedures: ["Dental Implants", "Teeth Whitening", "Smile Design"],
    tags: ["EN - FR", "Same Day Booking"],
    languages: ["English", "French"],
    coords: { lat: 19.3478, lng: -99.1872 },
  },
];

export function initializeDentistData() {
  if (typeof window !== "undefined") {
    const existing = localStorage.getItem("dentists_data");
    if (!existing) {
      localStorage.setItem("dentists_data", JSON.stringify(DEMO_DENTISTS));
    }
  }
}

export function getDentistsFromStorage(): Dentist[] {
  if (typeof window === "undefined") return DEMO_DENTISTS;

  try {
    const data = localStorage.getItem("dentists_data");
    return data ? JSON.parse(data) : DEMO_DENTISTS;
  } catch {
    return DEMO_DENTISTS;
  }
}
