import { Dentist } from "@/app/(marketing)/_components/module/DentistAllComponents/types";

const makeRating = (value: number, count: number) => ({
  google: value,
  googleReviewCount: count,
  doctoralia: null,
  doctoraliaReviewCount: null,
  combined: value,
});

const makeLocation = (city: string, fullAddress: string) => ({
  city,
  country: "Mexico",
  fullAddress,
  googleMapsUrl: null,
});

export const DEMO_DENTISTS: Dentist[] = [
  {
    id: "dr-ava-johnson",
    name: "Dr. Ava Johnson",
    slug: "dr-ava-johnson",
    specialty: "Veneers Specialist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=ava-johnson",
    backendId: "demo-1",
    country: "Mexico",
    price: 1500,
    rdvScore: 100,
    languages: ["English", "Spanish"],
    surpriseGuarantee: true,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: true,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(5.0, 45),
    location: makeLocation("Mexico City", "Mexico City, Mexico"),
    coords: { lat: 19.4326, lng: -99.1332 },
  },
  {
    id: "dr-sarah-thompson",
    name: "Dr. Sarah Thompson",
    slug: "dr-sarah-thompson",
    specialty: "Orthodontist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=sarah-thompson",
    backendId: "demo-2",
    country: "Mexico",
    price: 1500,
    rdvScore: 100,
    languages: ["English", "Spanish"],
    surpriseGuarantee: true,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: true,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.9, 48),
    location: makeLocation("Polanco", "Polanco, Mexico City, Mexico"),
    coords: { lat: 19.4326, lng: -99.1733 },
  },
  {
    id: "dr-emily-carter",
    name: "Dr. Emily Carter",
    slug: "dr-emily-carter",
    specialty: "Restorative Dentist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=emily-carter",
    backendId: "demo-3",
    country: "Mexico",
    price: 1350,
    rdvScore: 98,
    languages: ["English", "Spanish"],
    surpriseGuarantee: false,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: true,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.9, 31),
    location: makeLocation("Roma Norte", "Roma Norte, Mexico City, Mexico"),
    coords: { lat: 19.4146, lng: -99.1622 },
  },
  {
    id: "dr-julian-mora",
    name: "Dr. Julian Mora",
    slug: "dr-julian-mora",
    specialty: "Implant Dentist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=julian-mora",
    backendId: "demo-4",
    country: "Mexico",
    price: 1600,
    rdvScore: 96,
    languages: ["English"],
    surpriseGuarantee: true,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: true,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.8, 29),
    location: makeLocation("Roma Norte", "Roma Norte, Mexico City, Mexico"),
    coords: { lat: 19.4098, lng: -99.1568 },
  },
  {
    id: "dr-ana-lopez",
    name: "Dr. Ana Lopez",
    slug: "dr-ana-lopez",
    specialty: "Cosmetic Dentist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=ana-lopez",
    backendId: "demo-5",
    country: "Mexico",
    price: 1200,
    rdvScore: 94,
    languages: ["English", "Spanish"],
    surpriseGuarantee: false,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: false,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.7, 22),
    location: makeLocation("Coyoacan", "Coyoacan, Mexico City, Mexico"),
    coords: { lat: 19.3509, lng: -99.1611 },
  },
  {
    id: "dr-isaac-reyes",
    name: "Dr. Isaac Reyes",
    slug: "dr-isaac-reyes",
    specialty: "General Dentist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=isaac-reyes",
    backendId: "demo-6",
    country: "Mexico",
    price: 980,
    rdvScore: 92,
    languages: ["English", "Spanish"],
    surpriseGuarantee: true,
    verificationPhase: {
      currentPhase: "OPERATIONS",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: false,
      isClinicDepthVerified: false,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.6, 18),
    location: makeLocation("Del Valle", "Del Valle, Mexico City, Mexico"),
    coords: { lat: 19.3847, lng: -99.1629 },
  },
  {
    id: "dr-lucia-gomez",
    name: "Dr. Lucia Gomez",
    slug: "dr-lucia-gomez",
    specialty: "Periodontist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=lucia-gomez",
    backendId: "demo-7",
    country: "Mexico",
    price: 1100,
    rdvScore: 90,
    languages: ["English", "Spanish"],
    surpriseGuarantee: false,
    verificationPhase: {
      currentPhase: "OPERATIONS",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: false,
      isClinicDepthVerified: false,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.5, 15),
    location: makeLocation("Napoles", "Napoles, Mexico City, Mexico"),
    coords: { lat: 19.3929, lng: -99.1768 },
  },
  {
    id: "dr-michael-chen",
    name: "Dr. Michael Chen",
    slug: "dr-michael-chen",
    specialty: "Orthodontist",
    clinicName: null,
    phone: null,
    status: "VERIFIED",
    isClaimable: false,
    claimedByUserId: null,
    membershipPlan: null,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    image: "https://i.pravatar.cc/150?u=michael-chen",
    backendId: "demo-8",
    country: "Mexico",
    price: 1450,
    rdvScore: 97,
    languages: ["English", "French"],
    surpriseGuarantee: false,
    verificationPhase: {
      currentPhase: "CLINIC",
      nextPhase: "CLINIC",
      isLicenseVerified: true,
      isOperationsVerified: true,
      isClinicDepthVerified: true,
    },
    accountType: "REGISTERED",
    isClaimed: false,
    isVerified: true,
    rating: makeRating(4.8, 36),
    location: makeLocation("San Angel", "San Angel, Mexico City, Mexico"),
    coords: { lat: 19.3478, lng: -99.1872 },
  },
];

export function initializeDentistData() {
  if (typeof window !== "undefined") {
    const existing = localStorage.getItem("dentists_data");
    if (!existing) {
      localStorage.setItem("dentists_data", JSON.stringify(DEMO_DENTISTS));
    }
  }
}

export function getDentistsFromStorage(): Dentist[] {
  if (typeof window === "undefined") return DEMO_DENTISTS;

  try {
    const data = localStorage.getItem("dentists_data");
    return data ? JSON.parse(data) : DEMO_DENTISTS;
  } catch {
    return DEMO_DENTISTS;
  }
}
