export const endpoints = {
  auth: {
    registerPatient: "/auth/register/patient",
    verifyEmail: "/auth/verify-email",
    login: "/auth/login",
    verify2fa: "/auth/verify-2fa",
    resendOtp: "/auth/resend-otp",
    loginAdmin: "/auth/login/admin",
    googleLogin: "/auth/login/google",
    getSession: "/auth/current-user-session",
    logout: "/auth/logout",
  },
  patients: {
    register: "/auth/register/patient",
    personalizeData: "/patients/personalize-data",
  },
  dentists: {
    profile: "/dentists/profile",
    register: "/dentists/register",
    professionalData: "/dentists/professional-data",
    verifyLicenseCheck: "/dentists/verify-license/check",
    verifyLicenseSubmit: "/dentists/verify-license/submit",
    verifyOperationsSubmit: "/dentists/verify-operations/submit",
    verifyClinicDepthSubmit: "/dentists/verify-clinic-depth/submit",
    progress: "/dentists/progress",
    overview: "/dentists/overview",
    directoryList: "/dentists/directory",
    directoryAdd: "/dentists/directory/add",
    directoryDetail: (slug: string) => `/dentists/directory/${slug}`,
    directoryClaim: (slug: string) => `/dentists/directory/${slug}/claim`,
    directorySendClaimOtp: "/dentists/directory/claim/send-otp",
    directoryCheckoutSession: "/stripe/create-checkout-session",
    directoryConsultation: (slug: string) => `/dentists/directory/${slug}/request-consultation`,
    patients: "/dentists/patients",
    patientDetail: (id: string | number) => `/dentists/patients/${id}`,
  },
  procedures: {
    dentist: "/procedures/dentist",
    dentistCsv: "/procedures/dentist/csv",
    deleteDentistProcedure: (id: string | number) => `/procedures/dentist/${id}`,
    global: "/procedures/global",
    globalCsv: "/procedures/global/csv",
  },
  admin: {
    verifications: "/admin/verifications",
    verifyLicense: (id: string | number) => `/admin/verify-license/${id}`,
    verifyOperations: (id: string | number) => `/admin/verify-operations/${id}`,
    verifyClinicDepth: (id: string | number) => `/admin/verify-clinic-depth/${id}`,
    verifyPhase: (id: string | number) => `/admin/verify-phase/${id}`,
    verificationWeights: "/admin/verification-weights",
    dentists: "/admin/dentists",
    dentistProfile: (id: string | number) => `/admin/dentists/${id}`,
    dentistVerificationPhases: (id: string | number) => `/admin/dentist-verification/${id}`,
    uploadDentistDirectory: "/admin/dentist-directory/upload",
    patients: "/admin/patients",
    patientDetail: (id: string | number) => `/admin/patients/${id}`,
    overview: "/admin/overview",
  },
  specialties: {
    getSpecialties: "/specialties",
    getSpecialtyBySlug: (slug: string) => `/specialties/${slug}`,
    createSpecialty: "/specialties",
    updateSpecialty: (id: string) => `/specialties/${id}`,
    deleteSpecialty: (id: string) => `/specialties/${id}`,
    uploadSpecialties: "/specialties/upload",
  },
  consultations: {
    intake: "/consultations/intake",
    updateIntake: (id: string | number) => `/consultations/intake/${id}`,
    confirm: "/consultations/confirm",
    patient: "/consultations/patient",
    dentist: "/consultations/dentist",
    byId: (id: string | number) => `/consultations/${id}`,
    token: (id: string | number) => `/consultations/${id}/token`,
    respond: (id: string | number) => `/consultations/${id}/respond`,
    schedule: (id: string | number) => `/consultations/${id}/schedule`,
    cancel: (id: string | number) => `/consultations/${id}/cancel`,
    reschedule: (id: string | number) => `/consultations/${id}/reschedule`,
    updateStatus: (id: string | number) => `/consultations/${id}`,
    messages: (id: string | number) => `/consultations/${id}/messages`,
  },
  treatmentPlans: {
    propose: "/treatment-plans",
    patient: "/treatment-plans/patient",
    dentist: "/treatment-plans/dentist",
    byId: (id: string | number) => `/treatment-plans/${id}`,
    decision: (id: string | number) => `/treatment-plans/${id}/decision`,
  },
  users: {
    me: "/users/me",
    updatePatientProfile: "/users/profile/patient",
    updateDentistProfile: "/users/profile/dentist",
    updateAdminProfile: "/users/profile/admin",
    changePassword: "/users/change-password",
  },
} as const;
